name: Python CI


# Trigger the workflow on any push to the main branch or pull request
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest  # Use the latest Ubuntu runner, the code can be run on any OS

        steps:
            # Step 1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2
              
            # Step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                    python-version: '3.8'

            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            # Step 4: Run unit tests
            - name: Run tests
              run: pytest
